<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
<xsl:output method="text"/> 
	<xsl:template match="/table">
	 	/**
		* This is autogenerated class
		*/

		package chan.test.mongodb.beans;
		
		public class <xsl:value-of select="@name" /> {
			
			<xsl:for-each select="column">				
				<xsl:variable name="type" select="@type" />
				<xsl:variable name="name" select="@name" />
			
				private <xsl:call-template name="typeandname" />;
				public void set<xsl:value-of select="$name" /> (<xsl:call-template name="typeandname" />) {
					this.<xsl:value-of select="$name" /> =  <xsl:value-of select="$name" />;
				}
				
				public <xsl:value-of select="@type" /> get<xsl:value-of select="$name" /> () {
					return this.<xsl:value-of select="$name" />;
				}
			</xsl:for-each>
			
			
		}
	 </xsl:template>
	 
	 <xsl:template name="typeandname">
	 	<xsl:value-of select="@type" /> <xsl:text> </xsl:text> <xsl:value-of select="@name" />
	 </xsl:template>
</xsl:stylesheet>